blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/open-telemetry/community/blob/main/SECURITY.md
    about: Report security vulnerabilities privately
  - name: OpenTelemetry Security SIG
    url: https://docs.google.com/document/d/1P2xejC7lEkOV_Z-8E0oZPXLK5HOnUPNuRqKP0ZQ5fpg
    about: Join our weekly Security SIG meetings
  - name: Slack Channel
    url: https://cloud-native.slack.com/archives/C05A85QC281
    about: Chat with the Security SIG on Slack (#otel-sig-security)
