name: General Issue
description: Report a general issue or request related to the Security SIG
title: "[General]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. This template is for general issues related to the OpenTelemetry Security SIG.

        For security vulnerabilities, please use the Security Issue template or report privately to security@opentelemetry.io.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Bug report
        - Feature request
        - Documentation improvement
        - Process improvement
        - Question
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the issue
      placeholder: Describe the issue in detail
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. Step three

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have suggestions for how to address this issue, please describe them
      placeholder: Describe your proposed solution or approach

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: Add any other context, screenshots, or relevant information

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with thumbs up to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
