name: General Issue
description: General questions, discussions, or issues related to the Security SIG
title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue with the OpenTelemetry Security SIG!

        This template is for general questions, discussions, or issues related to the Security SIG's work.

        For security vulnerabilities, please use the **Security Issue** template instead.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question
        - Discussion
        - Documentation Request
        - Process Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of your question or issue.
      placeholder: Describe your question or issue
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might be helpful for understanding your issue.
      placeholder: Additional context, background information, etc.

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other information you think may be relevant.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with thumbs up to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
