name: Security Issue
description: Report a security-related concern or vulnerability
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a security issue. This template is for general security concerns related to the OpenTelemetry project.

        **WARNING: If you believe you have found a security vulnerability, please do NOT create a public issue. Instead, please report it privately by emailing security@opentelemetry.io or following the [security reporting guidelines](https://github.com/open-telemetry/community/blob/main/SECURITY.md).**

        This template is for:
        - Security documentation improvements
        - Security process discussions
        - Security tooling suggestions
        - General security-related questions or concerns

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of security issue is this?
      options:
        - Security documentation improvement
        - Security process discussion
        - Security tooling suggestion
        - Security audit follow-up
        - General security concern
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the security issue or concern
      placeholder: Describe the security issue or concern in detail
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which OpenTelemetry components or areas are affected?
      placeholder: List the components, repositories, or areas affected by this security issue

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this security issue?
      placeholder: Describe the potential security impact

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have suggestions for how to address this issue, please describe them
      placeholder: Describe your proposed solution or approach

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: Add any other context, screenshots, or relevant information

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with thumbs up to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
